# Site settings
title: City of Los Angeles Mayoral Dashboard
email: "mayor.opendata@lacity.org"
description: The Mayor's Dashboard tracks key metrics and outcomes from the City of Los Angeles. The platform is open-source and easily reusable; contact us if your city is interested in deploying it.
baseurl: "/bradley-tower"
url: "http://mobi-la.github.io/bradley-tower/" # the base hostname & protocol for your site
twitter_username: mobi-la
github_username:  mobi-la

# Build settings
markdown: kramdown
permalink: none
